export const groups = [
  { name: "Gruppo A", teams: ["🇲🇽 Mexico", "🇿🇦 South Africa", "🇰🇷 South Korea", "🇨🇿 Czechia"] },
  { name: "Gruppo B", teams: ["🇨🇦 Canada", "🇧🇦 Bosnia and Herzegovina", "🇶🇦 Qatar", "🇨🇭 Switzerland"] },
  { name: "Gruppo C", teams: ["🇧🇷 Brazil", "🇭🇹 Haiti", "🇲🇦 Morocco", "🏴 Scotland"] },
  { name: "Gruppo D", teams: ["🇺🇸 United States", "🇦🇺 Australia", "🇵🇾 Paraguay", "🇹🇷 Türkiye"] },
  { name: "Gruppo E", teams: ["🇨🇼 Curaçao", "🇪🇨 Ecuador", "🇩🇪 Germany", "🇨🇮 Ivory Coast"] },
  { name: "Gruppo F", teams: ["🇳🇱 Netherlands", "🇯🇵 Japan", "🇸🇪 Sweden", "🇹🇳 Tunisia"] },
  { name: "Gruppo G", teams: ["🇧🇪 Belgium", "🇪🇬 Egypt", "🇮🇷 Iran", "🇳🇿 New Zealand"] },
  { name: "Gruppo H", teams: ["🇨🇻 Cape Verde", "🇸🇦 Saudi Arabia", "🇪🇸 Spain", "🇺🇾 Uruguay"] },
  { name: "Gruppo I", teams: ["🇫🇷 France", "🇳🇴 Norway", "🇸🇳 Senegal", "🇮🇶 Iraq"] },
  { name: "Gruppo J", teams: ["🇦🇷 Argentina", "🇩🇿 Algeria", "🇦🇹 Austria", "🇯🇴 Jordan"] },
  { name: "Gruppo K", teams: ["🇵🇹 Portugal", "🇨🇩 DR Congo", "🇨🇴 Colombia", "🇺🇿 Uzbekistan"] },
  { name: "Gruppo L", teams: ["🏴 England", "🇭🇷 Croatia", "🇬🇭 Ghana", "🇵🇦 Panama"] },
];

const kickoffET = (date, time) => `${date}T${time}:00-04:00`;

// Calendario ufficiale FIFA 2026 aggiornato dal PDF.
// IMPORTANTE: gli ID m1...m72 sono mantenuti come nel vecchio data.js
// per non scollegare i pronostici già salvati in Supabase.
export const matches = [
  { id: "m1", matchNumber: 1, stage: "group", group: "Gruppo A", date: "2026-06-11", kickoff: kickoffET("2026-06-11", "15:00"), home: "🇲🇽 Mexico", away: "🇿🇦 South Africa" },
  { id: "m2", matchNumber: 2, stage: "group", group: "Gruppo A", date: "2026-06-11", kickoff: kickoffET("2026-06-11", "22:00"), home: "🇰🇷 South Korea", away: "🇨🇿 Czechia" },
  { id: "m3", matchNumber: 28, stage: "group", group: "Gruppo A", date: "2026-06-18", kickoff: kickoffET("2026-06-18", "21:00"), home: "🇲🇽 Mexico", away: "🇰🇷 South Korea" },
  { id: "m4", matchNumber: 25, stage: "group", group: "Gruppo A", date: "2026-06-18", kickoff: kickoffET("2026-06-18", "12:00"), home: "🇨🇿 Czechia", away: "🇿🇦 South Africa" },
  { id: "m5", matchNumber: 53, stage: "group", group: "Gruppo A", date: "2026-06-24", kickoff: kickoffET("2026-06-24", "21:00"), home: "🇨🇿 Czechia", away: "🇲🇽 Mexico" },
  { id: "m6", matchNumber: 54, stage: "group", group: "Gruppo A", date: "2026-06-24", kickoff: kickoffET("2026-06-24", "21:00"), home: "🇿🇦 South Africa", away: "🇰🇷 South Korea" },
  { id: "m7", matchNumber: 3, stage: "group", group: "Gruppo B", date: "2026-06-12", kickoff: kickoffET("2026-06-12", "15:00"), home: "🇨🇦 Canada", away: "🇧🇦 Bosnia and Herzegovina" },
  { id: "m8", matchNumber: 8, stage: "group", group: "Gruppo B", date: "2026-06-13", kickoff: kickoffET("2026-06-13", "15:00"), home: "🇶🇦 Qatar", away: "🇨🇭 Switzerland" },
  { id: "m9", matchNumber: 27, stage: "group", group: "Gruppo B", date: "2026-06-18", kickoff: kickoffET("2026-06-18", "18:00"), home: "🇨🇦 Canada", away: "🇶🇦 Qatar" },
  { id: "m10", matchNumber: 26, stage: "group", group: "Gruppo B", date: "2026-06-18", kickoff: kickoffET("2026-06-18", "15:00"), home: "🇨🇭 Switzerland", away: "🇧🇦 Bosnia and Herzegovina" },
  { id: "m11", matchNumber: 51, stage: "group", group: "Gruppo B", date: "2026-06-24", kickoff: kickoffET("2026-06-24", "15:00"), home: "🇨🇭 Switzerland", away: "🇨🇦 Canada" },
  { id: "m12", matchNumber: 52, stage: "group", group: "Gruppo B", date: "2026-06-24", kickoff: kickoffET("2026-06-24", "15:00"), home: "🇧🇦 Bosnia and Herzegovina", away: "🇶🇦 Qatar" },
  { id: "m13", matchNumber: 29, stage: "group", group: "Gruppo C", date: "2026-06-19", kickoff: kickoffET("2026-06-19", "20:30"), home: "🇧🇷 Brazil", away: "🇭🇹 Haiti" },
  { id: "m14", matchNumber: 30, stage: "group", group: "Gruppo C", date: "2026-06-19", kickoff: kickoffET("2026-06-19", "18:00"), home: "🇲🇦 Morocco", away: "🏴 Scotland", officialOrderReversed: true },
  { id: "m15", matchNumber: 7, stage: "group", group: "Gruppo C", date: "2026-06-13", kickoff: kickoffET("2026-06-13", "18:00"), home: "🇧🇷 Brazil", away: "🇲🇦 Morocco" },
  { id: "m16", matchNumber: 5, stage: "group", group: "Gruppo C", date: "2026-06-13", kickoff: kickoffET("2026-06-13", "21:00"), home: "🏴 Scotland", away: "🇭🇹 Haiti", officialOrderReversed: true },
  { id: "m17", matchNumber: 49, stage: "group", group: "Gruppo C", date: "2026-06-24", kickoff: kickoffET("2026-06-24", "18:00"), home: "🏴 Scotland", away: "🇧🇷 Brazil" },
  { id: "m18", matchNumber: 50, stage: "group", group: "Gruppo C", date: "2026-06-24", kickoff: kickoffET("2026-06-24", "18:00"), home: "🇭🇹 Haiti", away: "🇲🇦 Morocco", officialOrderReversed: true },
  { id: "m19", matchNumber: 32, stage: "group", group: "Gruppo D", date: "2026-06-19", kickoff: kickoffET("2026-06-19", "15:00"), home: "🇺🇸 United States", away: "🇦🇺 Australia" },
  { id: "m20", matchNumber: 31, stage: "group", group: "Gruppo D", date: "2026-06-19", kickoff: kickoffET("2026-06-19", "23:00"), home: "🇵🇾 Paraguay", away: "🇹🇷 Türkiye", officialOrderReversed: true },
  { id: "m21", matchNumber: 4, stage: "group", group: "Gruppo D", date: "2026-06-12", kickoff: kickoffET("2026-06-12", "21:00"), home: "🇺🇸 United States", away: "🇵🇾 Paraguay" },
  { id: "m22", matchNumber: 6, stage: "group", group: "Gruppo D", date: "2026-06-13", kickoff: kickoffET("2026-06-13", "00:00"), home: "🇹🇷 Türkiye", away: "🇦🇺 Australia", officialOrderReversed: true },
  { id: "m23", matchNumber: 59, stage: "group", group: "Gruppo D", date: "2026-06-25", kickoff: kickoffET("2026-06-25", "22:00"), home: "🇹🇷 Türkiye", away: "🇺🇸 United States" },
  { id: "m24", matchNumber: 60, stage: "group", group: "Gruppo D", date: "2026-06-25", kickoff: kickoffET("2026-06-25", "22:00"), home: "🇦🇺 Australia", away: "🇵🇾 Paraguay", officialOrderReversed: true },
  { id: "m25", matchNumber: 34, stage: "group", group: "Gruppo E", date: "2026-06-20", kickoff: kickoffET("2026-06-20", "20:00"), home: "🇨🇼 Curaçao", away: "🇪🇨 Ecuador", officialOrderReversed: true },
  { id: "m26", matchNumber: 33, stage: "group", group: "Gruppo E", date: "2026-06-20", kickoff: kickoffET("2026-06-20", "16:00"), home: "🇩🇪 Germany", away: "🇨🇮 Ivory Coast" },
  { id: "m27", matchNumber: 10, stage: "group", group: "Gruppo E", date: "2026-06-14", kickoff: kickoffET("2026-06-14", "13:00"), home: "🇨🇼 Curaçao", away: "🇩🇪 Germany", officialOrderReversed: true },
  { id: "m28", matchNumber: 9, stage: "group", group: "Gruppo E", date: "2026-06-14", kickoff: kickoffET("2026-06-14", "19:00"), home: "🇨🇮 Ivory Coast", away: "🇪🇨 Ecuador" },
  { id: "m29", matchNumber: 55, stage: "group", group: "Gruppo E", date: "2026-06-25", kickoff: kickoffET("2026-06-25", "16:00"), home: "🇨🇮 Ivory Coast", away: "🇨🇼 Curaçao", officialOrderReversed: true },
  { id: "m30", matchNumber: 56, stage: "group", group: "Gruppo E", date: "2026-06-25", kickoff: kickoffET("2026-06-25", "16:00"), home: "🇪🇨 Ecuador", away: "🇩🇪 Germany" },
  { id: "m31", matchNumber: 11, stage: "group", group: "Gruppo F", date: "2026-06-14", kickoff: kickoffET("2026-06-14", "16:00"), home: "🇳🇱 Netherlands", away: "🇯🇵 Japan" },
  { id: "m32", matchNumber: 12, stage: "group", group: "Gruppo F", date: "2026-06-14", kickoff: kickoffET("2026-06-14", "22:00"), home: "🇸🇪 Sweden", away: "🇹🇳 Tunisia" },
  { id: "m33", matchNumber: 35, stage: "group", group: "Gruppo F", date: "2026-06-20", kickoff: kickoffET("2026-06-20", "13:00"), home: "🇳🇱 Netherlands", away: "🇸🇪 Sweden" },
  { id: "m34", matchNumber: 36, stage: "group", group: "Gruppo F", date: "2026-06-20", kickoff: kickoffET("2026-06-20", "00:00"), home: "🇹🇳 Tunisia", away: "🇯🇵 Japan" },
  { id: "m35", matchNumber: 58, stage: "group", group: "Gruppo F", date: "2026-06-25", kickoff: kickoffET("2026-06-25", "19:00"), home: "🇹🇳 Tunisia", away: "🇳🇱 Netherlands" },
  { id: "m36", matchNumber: 57, stage: "group", group: "Gruppo F", date: "2026-06-25", kickoff: kickoffET("2026-06-25", "19:00"), home: "🇯🇵 Japan", away: "🇸🇪 Sweden" },
  { id: "m37", matchNumber: 16, stage: "group", group: "Gruppo G", date: "2026-06-15", kickoff: kickoffET("2026-06-15", "15:00"), home: "🇧🇪 Belgium", away: "🇪🇬 Egypt" },
  { id: "m38", matchNumber: 15, stage: "group", group: "Gruppo G", date: "2026-06-15", kickoff: kickoffET("2026-06-15", "21:00"), home: "🇮🇷 Iran", away: "🇳🇿 New Zealand" },
  { id: "m39", matchNumber: 39, stage: "group", group: "Gruppo G", date: "2026-06-21", kickoff: kickoffET("2026-06-21", "15:00"), home: "🇧🇪 Belgium", away: "🇮🇷 Iran" },
  { id: "m40", matchNumber: 40, stage: "group", group: "Gruppo G", date: "2026-06-21", kickoff: kickoffET("2026-06-21", "21:00"), home: "🇳🇿 New Zealand", away: "🇪🇬 Egypt" },
  { id: "m41", matchNumber: 64, stage: "group", group: "Gruppo G", date: "2026-06-26", kickoff: kickoffET("2026-06-26", "23:00"), home: "🇳🇿 New Zealand", away: "🇧🇪 Belgium" },
  { id: "m42", matchNumber: 63, stage: "group", group: "Gruppo G", date: "2026-06-26", kickoff: kickoffET("2026-06-26", "23:00"), home: "🇪🇬 Egypt", away: "🇮🇷 Iran" },
  { id: "m43", matchNumber: 65, stage: "group", group: "Gruppo H", date: "2026-06-26", kickoff: kickoffET("2026-06-26", "20:00"), home: "🇨🇻 Cape Verde", away: "🇸🇦 Saudi Arabia" },
  { id: "m44", matchNumber: 66, stage: "group", group: "Gruppo H", date: "2026-06-26", kickoff: kickoffET("2026-06-26", "20:00"), home: "🇪🇸 Spain", away: "🇺🇾 Uruguay", officialOrderReversed: true },
  { id: "m45", matchNumber: 14, stage: "group", group: "Gruppo H", date: "2026-06-15", kickoff: kickoffET("2026-06-15", "12:00"), home: "🇨🇻 Cape Verde", away: "🇪🇸 Spain", officialOrderReversed: true },
  { id: "m46", matchNumber: 13, stage: "group", group: "Gruppo H", date: "2026-06-15", kickoff: kickoffET("2026-06-15", "18:00"), home: "🇺🇾 Uruguay", away: "🇸🇦 Saudi Arabia", officialOrderReversed: true },
  { id: "m47", matchNumber: 37, stage: "group", group: "Gruppo H", date: "2026-06-21", kickoff: kickoffET("2026-06-21", "18:00"), home: "🇺🇾 Uruguay", away: "🇨🇻 Cape Verde" },
  { id: "m48", matchNumber: 38, stage: "group", group: "Gruppo H", date: "2026-06-21", kickoff: kickoffET("2026-06-21", "12:00"), home: "🇸🇦 Saudi Arabia", away: "🇪🇸 Spain", officialOrderReversed: true },
  { id: "m49", matchNumber: 61, stage: "group", group: "Gruppo I", date: "2026-06-26", kickoff: kickoffET("2026-06-26", "15:00"), home: "🇫🇷 France", away: "🇳🇴 Norway", officialOrderReversed: true },
  { id: "m50", matchNumber: 62, stage: "group", group: "Gruppo I", date: "2026-06-26", kickoff: kickoffET("2026-06-26", "15:00"), home: "🇸🇳 Senegal", away: "🇮🇶 Iraq" },
  { id: "m51", matchNumber: 17, stage: "group", group: "Gruppo I", date: "2026-06-16", kickoff: kickoffET("2026-06-16", "15:00"), home: "🇫🇷 France", away: "🇸🇳 Senegal" },
  { id: "m52", matchNumber: 18, stage: "group", group: "Gruppo I", date: "2026-06-16", kickoff: kickoffET("2026-06-16", "18:00"), home: "🇮🇶 Iraq", away: "🇳🇴 Norway" },
  { id: "m53", matchNumber: 42, stage: "group", group: "Gruppo I", date: "2026-06-22", kickoff: kickoffET("2026-06-22", "17:00"), home: "🇮🇶 Iraq", away: "🇫🇷 France", officialOrderReversed: true },
  { id: "m54", matchNumber: 41, stage: "group", group: "Gruppo I", date: "2026-06-22", kickoff: kickoffET("2026-06-22", "20:00"), home: "🇳🇴 Norway", away: "🇸🇳 Senegal" },
  { id: "m55", matchNumber: 19, stage: "group", group: "Gruppo J", date: "2026-06-16", kickoff: kickoffET("2026-06-16", "21:00"), home: "🇦🇷 Argentina", away: "🇩🇿 Algeria" },
  { id: "m56", matchNumber: 20, stage: "group", group: "Gruppo J", date: "2026-06-16", kickoff: kickoffET("2026-06-16", "00:00"), home: "🇦🇹 Austria", away: "🇯🇴 Jordan" },
  { id: "m57", matchNumber: 43, stage: "group", group: "Gruppo J", date: "2026-06-22", kickoff: kickoffET("2026-06-22", "13:00"), home: "🇦🇷 Argentina", away: "🇦🇹 Austria" },
  { id: "m58", matchNumber: 44, stage: "group", group: "Gruppo J", date: "2026-06-22", kickoff: kickoffET("2026-06-22", "23:00"), home: "🇯🇴 Jordan", away: "🇩🇿 Algeria" },
  { id: "m59", matchNumber: 70, stage: "group", group: "Gruppo J", date: "2026-06-27", kickoff: kickoffET("2026-06-27", "22:00"), home: "🇯🇴 Jordan", away: "🇦🇷 Argentina" },
  { id: "m60", matchNumber: 69, stage: "group", group: "Gruppo J", date: "2026-06-27", kickoff: kickoffET("2026-06-27", "22:00"), home: "🇩🇿 Algeria", away: "🇦🇹 Austria" },
  { id: "m61", matchNumber: 23, stage: "group", group: "Gruppo K", date: "2026-06-17", kickoff: kickoffET("2026-06-17", "13:00"), home: "🇵🇹 Portugal", away: "🇨🇩 DR Congo" },
  { id: "m62", matchNumber: 24, stage: "group", group: "Gruppo K", date: "2026-06-17", kickoff: kickoffET("2026-06-17", "22:00"), home: "🇨🇴 Colombia", away: "🇺🇿 Uzbekistan", officialOrderReversed: true },
  { id: "m63", matchNumber: 71, stage: "group", group: "Gruppo K", date: "2026-06-27", kickoff: kickoffET("2026-06-27", "19:30"), home: "🇵🇹 Portugal", away: "🇨🇴 Colombia", officialOrderReversed: true },
  { id: "m64", matchNumber: 72, stage: "group", group: "Gruppo K", date: "2026-06-27", kickoff: kickoffET("2026-06-27", "19:30"), home: "🇺🇿 Uzbekistan", away: "🇨🇩 DR Congo", officialOrderReversed: true },
  { id: "m65", matchNumber: 47, stage: "group", group: "Gruppo K", date: "2026-06-23", kickoff: kickoffET("2026-06-23", "13:00"), home: "🇺🇿 Uzbekistan", away: "🇵🇹 Portugal", officialOrderReversed: true },
  { id: "m66", matchNumber: 48, stage: "group", group: "Gruppo K", date: "2026-06-23", kickoff: kickoffET("2026-06-23", "22:00"), home: "🇨🇩 DR Congo", away: "🇨🇴 Colombia", officialOrderReversed: true },
  { id: "m67", matchNumber: 22, stage: "group", group: "Gruppo L", date: "2026-06-17", kickoff: kickoffET("2026-06-17", "16:00"), home: "🏴 England", away: "🇭🇷 Croatia" },
  { id: "m68", matchNumber: 21, stage: "group", group: "Gruppo L", date: "2026-06-17", kickoff: kickoffET("2026-06-17", "19:00"), home: "🇬🇭 Ghana", away: "🇵🇦 Panama" },
  { id: "m69", matchNumber: 45, stage: "group", group: "Gruppo L", date: "2026-06-23", kickoff: kickoffET("2026-06-23", "16:00"), home: "🏴 England", away: "🇬🇭 Ghana" },
  { id: "m70", matchNumber: 46, stage: "group", group: "Gruppo L", date: "2026-06-23", kickoff: kickoffET("2026-06-23", "19:00"), home: "🇵🇦 Panama", away: "🇭🇷 Croatia" },
  { id: "m71", matchNumber: 67, stage: "group", group: "Gruppo L", date: "2026-06-27", kickoff: kickoffET("2026-06-27", "17:00"), home: "🇵🇦 Panama", away: "🏴 England" },
  { id: "m72", matchNumber: 68, stage: "group", group: "Gruppo L", date: "2026-06-27", kickoff: kickoffET("2026-06-27", "17:00"), home: "🇭🇷 Croatia", away: "🇬🇭 Ghana" },
];

export const knockoutRounds = [
  { round: "Sedicesimi", matches: ["2A - 2B", "1E - 3ABCDF", "1F - 2C", "1C - 2F", "1I - 3CDFGH", "2E - 2I", "1A - 3CEFHI", "1L - 3EHIJK", "1D - 3BEFIJ", "1G - 3AEHIJ", "2K - 2L", "1H - 2J", "1B - 3EFGIJ", "1J - 2H", "1K - 3DEIJL", "2D - 2G"] },
  { round: "Ottavi", matches: ["Vincente S2 - Vincente S5", "Vincente S1 - Vincente S3", "Vincente S4 - Vincente S6", "Vincente S7 - Vincente S8", "Vincente S11 - Vincente S12", "Vincente S9 - Vincente S10", "Vincente S14 - Vincente S16", "Vincente S13 - Vincente S15"] },
  { round: "Quarti", matches: ["Vincente O1 - Vincente O2", "Vincente O5 - Vincente O6", "Vincente O3 - Vincente O4", "Vincente O7 - Vincente O8"] },
  { round: "Semifinali", matches: ["Vincente Q1 - Vincente Q2", "Vincente Q3 - Vincente Q4"] },
  { round: "Finale 3° posto", matches: ["Perdente SF1 - Perdente SF2"] },
  { round: "Finale", matches: ["Vincente SF1 - Vincente SF2"] },
];


export const topScorers = [
  "🇲🇽 Santiago Giménez (Mexico)",
  "🇲🇽 Raúl Jiménez (Mexico)",
  "🇲🇽 Hirving Lozano (Mexico)",
  "🇲🇽 Henry Martín (Mexico)",
  "🇲🇽 Uriel Antuna (Mexico)",
  "🇲🇽 Julián Quiñones (Mexico)",
  "🇲🇽 Roberto Alvarado (Mexico)",
  "🇲🇽 Alexis Vega (Mexico)",
  "🇿🇦 Percy Tau (South Africa)",
  "🇿🇦 Lyle Foster (South Africa)",
  "🇿🇦 Evidence Makgopa (South Africa)",
  "🇿🇦 Themba Zwane (South Africa)",
  "🇿🇦 Zakhele Lepasa (South Africa)",
  "🇿🇦 Iqraam Rayners (South Africa)",
  "🇿🇦 Oswin Appollis (South Africa)",
  "🇿🇦 Teboho Mokoena (South Africa)",
  "🇰🇷 Son Heung-min (South Korea)",
  "🇰🇷 Hwang Hee-chan (South Korea)",
  "🇰🇷 Lee Kang-in (South Korea)",
  "🇰🇷 Cho Gue-sung (South Korea)",
  "🇰🇷 Oh Hyeon-gyu (South Korea)",
  "🇰🇷 Hwang Ui-jo (South Korea)",
  "🇰🇷 Jeong Woo-yeong (South Korea)",
  "🇰🇷 Hong Hyun-seok (South Korea)",
  "🇨🇿 Patrik Schick (Czechia)",
  "🇨🇿 Adam Hložek (Czechia)",
  "🇨🇿 Tomáš Čvančara (Czechia)",
  "🇨🇿 Mojmír Chytil (Czechia)",
  "🇨🇿 Václav Černý (Czechia)",
  "🇨🇿 Lukáš Provod (Czechia)",
  "🇨🇿 Jan Kuchta (Czechia)",
  "🇨🇿 Antonín Barák (Czechia)",
  "🇨🇦 Jonathan David (Canada)",
  "🇨🇦 Alphonso Davies (Canada)",
  "🇨🇦 Cyle Larin (Canada)",
  "🇨🇦 Tajon Buchanan (Canada)",
  "🇨🇦 Jacob Shaffelburg (Canada)",
  "🇨🇦 Ismaël Koné (Canada)",
  "🇨🇦 Jonathan Osorio (Canada)",
  "🇨🇦 Liam Millar (Canada)",
  "🇧🇦 Edin Džeko (Bosnia and Herzegovina)",
  "🇧🇦 Ermedin Demirović (Bosnia and Herzegovina)",
  "🇧🇦 Haris Tabaković (Bosnia and Herzegovina)",
  "🇧🇦 Smail Prevljak (Bosnia and Herzegovina)",
  "🇧🇦 Benjamin Tahirović (Bosnia and Herzegovina)",
  "🇧🇦 Amar Dedić (Bosnia and Herzegovina)",
  "🇧🇦 Rade Krunić (Bosnia and Herzegovina)",
  "🇧🇦 Denis Huseinbašić (Bosnia and Herzegovina)",
  "🇶🇦 Akram Afif (Qatar)",
  "🇶🇦 Almoez Ali (Qatar)",
  "🇶🇦 Hassan Al-Haydos (Qatar)",
  "🇶🇦 Mohammed Muntari (Qatar)",
  "🇶🇦 Ahmed Alaaeldin (Qatar)",
  "🇶🇦 Yusuf Abdurisag (Qatar)",
  "🇶🇦 Assim Madibo (Qatar)",
  "🇶🇦 Abdulaziz Hatem (Qatar)",
  "🇨🇭 Breel Embolo (Switzerland)",
  "🇨🇭 Noah Okafor (Switzerland)",
  "🇨🇭 Zeki Amdouni (Switzerland)",
  "🇨🇭 Xherdan Shaqiri (Switzerland)",
  "🇨🇭 Ruben Vargas (Switzerland)",
  "🇨🇭 Dan Ndoye (Switzerland)",
  "🇨🇭 Renato Steffen (Switzerland)",
  "🇨🇭 Granit Xhaka (Switzerland)",
  "🇧🇷 Vinícius Jr (Brazil)",
  "🇧🇷 Rodrygo (Brazil)",
  "🇧🇷 Endrick (Brazil)",
  "🇧🇷 Raphinha (Brazil)",
  "🇧🇷 Gabriel Martinelli (Brazil)",
  "🇧🇷 Richarlison (Brazil)",
  "🇧🇷 Gabriel Jesus (Brazil)",
  "🇧🇷 Neymar (Brazil)",
  "🇧🇷 Lucas Paquetá (Brazil)",
  "🇧🇷 Bruno Guimarães (Brazil)",
  "🇭🇹 Duckens Nazon (Haiti)",
  "🇭🇹 Frantzdy Pierrot (Haiti)",
  "🇭🇹 Fafà Picault (Haiti)",
  "🇭🇹 Carnejy Antoine (Haiti)",
  "🇭🇹 Leverton Pierre (Haiti)",
  "🇭🇹 Derrick Etienne Jr (Haiti)",
  "🇭🇹 Danley Jean Jacques (Haiti)",
  "🇭🇹 Louicius Don Deedson (Haiti)",
  "🇲🇦 Youssef En-Nesyri (Morocco)",
  "🇲🇦 Achraf Hakimi (Morocco)",
  "🇲🇦 Hakim Ziyech (Morocco)",
  "🇲🇦 Sofiane Boufal (Morocco)",
  "🇲🇦 Amine Adli (Morocco)",
  "🇲🇦 Ayoub El Kaabi (Morocco)",
  "🇲🇦 Brahim Díaz (Morocco)",
  "🇲🇦 Soufiane Rahimi (Morocco)",
  "🇲🇦 Azzedine Ounahi (Morocco)",
  "🏴 Scott McTominay (Scotland)",
  "🏴 Che Adams (Scotland)",
  "🏴 Lyndon Dykes (Scotland)",
  "🏴 John McGinn (Scotland)",
  "🏴 Ryan Christie (Scotland)",
  "🏴 Lawrence Shankland (Scotland)",
  "🏴 Ben Doak (Scotland)",
  "🏴 Billy Gilmour (Scotland)",
  "🇺🇸 Christian Pulisic (United States)",
  "🇺🇸 Folarin Balogun (United States)",
  "🇺🇸 Timothy Weah (United States)",
  "🇺🇸 Giovanni Reyna (United States)",
  "🇺🇸 Ricardo Pepi (United States)",
  "🇺🇸 Brenden Aaronson (United States)",
  "🇺🇸 Haji Wright (United States)",
  "🇺🇸 Weston McKennie (United States)",
  "🇦🇺 Mitchell Duke (Australia)",
  "🇦🇺 Craig Goodwin (Australia)",
  "🇦🇺 Mathew Leckie (Australia)",
  "🇦🇺 Riley McGree (Australia)",
  "🇦🇺 Jackson Irvine (Australia)",
  "🇦🇺 Brandon Borrello (Australia)",
  "🇦🇺 Kusini Yengi (Australia)",
  "🇦🇺 Martin Boyle (Australia)",
  "🇵🇾 Miguel Almirón (Paraguay)",
  "🇵🇾 Julio Enciso (Paraguay)",
  "🇵🇾 Ramón Sosa (Paraguay)",
  "🇵🇾 Antonio Sanabria (Paraguay)",
  "🇵🇾 Gabriel Ávalos (Paraguay)",
  "🇵🇾 Matías Rojas (Paraguay)",
  "🇵🇾 Ángel Romero (Paraguay)",
  "🇵🇾 Adam Bareiro (Paraguay)",
  "🇹🇷 Hakan Çalhanoğlu (Türkiye)",
  "🇹🇷 Arda Güler (Türkiye)",
  "🇹🇷 Kerem Aktürkoğlu (Türkiye)",
  "🇹🇷 Cenk Tosun (Türkiye)",
  "🇹🇷 Barış Alper Yılmaz (Türkiye)",
  "🇹🇷 Yunus Akgün (Türkiye)",
  "🇹🇷 İrfan Can Kahveci (Türkiye)",
  "🇹🇷 Semih Kılıçsoy (Türkiye)",
  "🇨🇼 Leandro Bacuna (Curaçao)",
  "🇨🇼 Juninho Bacuna (Curaçao)",
  "🇨🇼 Jearl Margaritha (Curaçao)",
  "🇨🇼 Rangelo Janga (Curaçao)",
  "🇨🇼 Brandley Kuwas (Curaçao)",
  "🇨🇼 Gervane Kastaneer (Curaçao)",
  "🇨🇼 Jeremy Antonisse (Curaçao)",
  "🇨🇼 Kenji Gorré (Curaçao)",
  "🇪🇨 Enner Valencia (Ecuador)",
  "🇪🇨 Moisés Caicedo (Ecuador)",
  "🇪🇨 Piero Hincapié (Ecuador)",
  "🇪🇨 Kendry Páez (Ecuador)",
  "🇪🇨 Kevin Rodríguez (Ecuador)",
  "🇪🇨 Gonzalo Plata (Ecuador)",
  "🇪🇨 Ángel Mena (Ecuador)",
  "🇪🇨 Jeremy Sarmiento (Ecuador)",
  "🇩🇪 Florian Wirtz (Germany)",
  "🇩🇪 Kai Havertz (Germany)",
  "🇩🇪 Jamal Musiala (Germany)",
  "🇩🇪 Niclas Füllkrug (Germany)",
  "🇩🇪 Serge Gnabry (Germany)",
  "🇩🇪 Leroy Sané (Germany)",
  "🇩🇪 Thomas Müller (Germany)",
  "🇩🇪 Maximilian Beier (Germany)",
  "🇩🇪 Deniz Undav (Germany)",
  "🇨🇮 Sébastien Haller (Ivory Coast)",
  "🇨🇮 Simon Adingra (Ivory Coast)",
  "🇨🇮 Nicolas Pépé (Ivory Coast)",
  "🇨🇮 Wilfried Zaha (Ivory Coast)",
  "🇨🇮 Franck Kessié (Ivory Coast)",
  "🇨🇮 Oumar Diakité (Ivory Coast)",
  "🇨🇮 Karim Konaté (Ivory Coast)",
  "🇨🇮 Jean-Philippe Krasso (Ivory Coast)",
  "🇳🇱 Cody Gakpo (Netherlands)",
  "🇳🇱 Memphis Depay (Netherlands)",
  "🇳🇱 Xavi Simons (Netherlands)",
  "🇳🇱 Donyell Malen (Netherlands)",
  "🇳🇱 Brian Brobbey (Netherlands)",
  "🇳🇱 Wout Weghorst (Netherlands)",
  "🇳🇱 Steven Bergwijn (Netherlands)",
  "🇳🇱 Tijjani Reijnders (Netherlands)",
  "🇯🇵 Takefusa Kubo (Japan)",
  "🇯🇵 Kaoru Mitoma (Japan)",
  "🇯🇵 Takumi Minamino (Japan)",
  "🇯🇵 Daichi Kamada (Japan)",
  "🇯🇵 Ritsu Doan (Japan)",
  "🇯🇵 Ayase Ueda (Japan)",
  "🇯🇵 Kyogo Furuhashi (Japan)",
  "🇯🇵 Daizen Maeda (Japan)",
  "🇯🇵 Junya Ito (Japan)",
  "🇸🇪 Alexander Isak (Sweden)",
  "🇸🇪 Viktor Gyökeres (Sweden)",
  "🇸🇪 Dejan Kulusevski (Sweden)",
  "🇸🇪 Anthony Elanga (Sweden)",
  "🇸🇪 Emil Forsberg (Sweden)",
  "🇸🇪 Jesper Karlsson (Sweden)",
  "🇸🇪 Robin Quaison (Sweden)",
  "🇸🇪 Mattias Svanberg (Sweden)",
  "🇹🇳 Youssef Msakni (Tunisia)",
  "🇹🇳 Wahbi Khazri (Tunisia)",
  "🇹🇳 Hannibal Mejbri (Tunisia)",
  "🇹🇳 Elias Achouri (Tunisia)",
  "🇹🇳 Seifeddine Jaziri (Tunisia)",
  "🇹🇳 Haythem Jouini (Tunisia)",
  "🇹🇳 Ali Abdi (Tunisia)",
  "🇹🇳 Anis Ben Slimane (Tunisia)",
  "🇧🇪 Romelu Lukaku (Belgium)",
  "🇧🇪 Kevin De Bruyne (Belgium)",
  "🇧🇪 Jérémy Doku (Belgium)",
  "🇧🇪 Leandro Trossard (Belgium)",
  "🇧🇪 Loïs Openda (Belgium)",
  "🇧🇪 Charles De Ketelaere (Belgium)",
  "🇧🇪 Dodi Lukebakio (Belgium)",
  "🇧🇪 Youri Tielemans (Belgium)",
  "🇪🇬 Mohamed Salah (Egypt)",
  "🇪🇬 Mostafa Mohamed (Egypt)",
  "🇪🇬 Omar Marmoush (Egypt)",
  "🇪🇬 Trézéguet (Egypt)",
  "🇪🇬 Zizo (Egypt)",
  "🇪🇬 Emam Ashour (Egypt)",
  "🇪🇬 Mahmoud Kahraba (Egypt)",
  "🇪🇬 Ibrahim Adel (Egypt)",
  "🇮🇷 Mehdi Taremi (Iran)",
  "🇮🇷 Sardar Azmoun (Iran)",
  "🇮🇷 Alireza Jahanbakhsh (Iran)",
  "🇮🇷 Mehdi Ghayedi (Iran)",
  "🇮🇷 Saman Ghoddos (Iran)",
  "🇮🇷 Ali Gholizadeh (Iran)",
  "🇮🇷 Mohammad Mohebi (Iran)",
  "🇮🇷 Karim Ansarifard (Iran)",
  "🇳🇿 Chris Wood (New Zealand)",
  "🇳🇿 Ben Waine (New Zealand)",
  "🇳🇿 Kosta Barbarouses (New Zealand)",
  "🇳🇿 Sarpreet Singh (New Zealand)",
  "🇳🇿 Elijah Just (New Zealand)",
  "🇳🇿 Marco Rojas (New Zealand)",
  "🇳🇿 Callum McCowatt (New Zealand)",
  "🇳🇿 Matthew Garbett (New Zealand)",
  "🇨🇻 Ryan Mendes (Cape Verde)",
  "🇨🇻 Bebé (Cape Verde)",
  "🇨🇻 Jovane Cabral (Cape Verde)",
  "🇨🇻 Garry Rodrigues (Cape Verde)",
  "🇨🇻 Djaniny (Cape Verde)",
  "🇨🇻 Willy Semedo (Cape Verde)",
  "🇨🇻 Jamiro Monteiro (Cape Verde)",
  "🇨🇻 Kevin Pina (Cape Verde)",
  "🇸🇦 Salem Al-Dawsari (Saudi Arabia)",
  "🇸🇦 Firas Al-Buraikan (Saudi Arabia)",
  "🇸🇦 Saleh Al-Shehri (Saudi Arabia)",
  "🇸🇦 Abdulrahman Ghareeb (Saudi Arabia)",
  "🇸🇦 Sami Al-Najei (Saudi Arabia)",
  "🇸🇦 Hattan Bahebri (Saudi Arabia)",
  "🇸🇦 Ayman Yahya (Saudi Arabia)",
  "🇸🇦 Mohammed Kanno (Saudi Arabia)",
  "🇪🇸 Álvaro Morata (Spain)",
  "🇪🇸 Lamine Yamal (Spain)",
  "🇪🇸 Nico Williams (Spain)",
  "🇪🇸 Dani Olmo (Spain)",
  "🇪🇸 Pedri (Spain)",
  "🇪🇸 Mikel Oyarzabal (Spain)",
  "🇪🇸 Ferran Torres (Spain)",
  "🇪🇸 Joselu (Spain)",
  "🇪🇸 Fermín López (Spain)",
  "🇺🇾 Darwin Núñez (Uruguay)",
  "🇺🇾 Federico Valverde (Uruguay)",
  "🇺🇾 Luis Suárez (Uruguay)",
  "🇺🇾 Facundo Pellistri (Uruguay)",
  "🇺🇾 Nicolás de la Cruz (Uruguay)",
  "🇺🇾 Giorgian de Arrascaeta (Uruguay)",
  "🇺🇾 Maximiliano Araújo (Uruguay)",
  "🇺🇾 Brian Rodríguez (Uruguay)",
  "🇫🇷 Kylian Mbappé (France)",
  "🇫🇷 Ousmane Dembélé (France)",
  "🇫🇷 Marcus Thuram (France)",
  "🇫🇷 Randal Kolo Muani (France)",
  "🇫🇷 Bradley Barcola (France)",
  "🇫🇷 Antoine Griezmann (France)",
  "🇫🇷 Kingsley Coman (France)",
  "🇫🇷 Christopher Nkunku (France)",
  "🇫🇷 Olivier Giroud (France)",
  "🇳🇴 Erling Haaland (Norway)",
  "🇳🇴 Martin Ødegaard (Norway)",
  "🇳🇴 Alexander Sørloth (Norway)",
  "🇳🇴 Antonio Nusa (Norway)",
  "🇳🇴 Jørgen Strand Larsen (Norway)",
  "🇳🇴 Oscar Bobb (Norway)",
  "🇳🇴 Sander Berge (Norway)",
  "🇳🇴 Kristian Thorstvedt (Norway)",
  "🇸🇳 Sadio Mané (Senegal)",
  "🇸🇳 Nicolas Jackson (Senegal)",
  "🇸🇳 Ismaïla Sarr (Senegal)",
  "🇸🇳 Habib Diallo (Senegal)",
  "🇸🇳 Boulaye Dia (Senegal)",
  "🇸🇳 Iliman Ndiaye (Senegal)",
  "🇸🇳 Krépin Diatta (Senegal)",
  "🇸🇳 Pape Matar Sarr (Senegal)",
  "🇮🇶 Aymen Hussein (Iraq)",
  "🇮🇶 Ali Al-Hamadi (Iraq)",
  "🇮🇶 Mohanad Ali (Iraq)",
  "🇮🇶 Ibrahim Bayesh (Iraq)",
  "🇮🇶 Amir Al-Ammari (Iraq)",
  "🇮🇶 Bashar Resan (Iraq)",
  "🇮🇶 Hussein Ali (Iraq)",
  "🇮🇶 Youssef Amyn (Iraq)",
  "🇦🇷 Lionel Messi (Argentina)",
  "🇦🇷 Lautaro Martínez (Argentina)",
  "🇦🇷 Julián Álvarez (Argentina)",
  "🇦🇷 Paulo Dybala (Argentina)",
  "🇦🇷 Alejandro Garnacho (Argentina)",
  "🇦🇷 Ángel Di María (Argentina)",
  "🇦🇷 Nicolás González (Argentina)",
  "🇦🇷 Giovanni Simeone (Argentina)",
  "🇦🇷 Thiago Almada (Argentina)",
  "🇩🇿 Riyad Mahrez (Algeria)",
  "🇩🇿 Amine Gouiri (Algeria)",
  "🇩🇿 Islam Slimani (Algeria)",
  "🇩🇿 Youcef Belaïli (Algeria)",
  "🇩🇿 Baghdad Bounedjah (Algeria)",
  "🇩🇿 Saïd Benrahma (Algeria)",
  "🇩🇿 Farès Chaïbi (Algeria)",
  "🇩🇿 Houssem Aouar (Algeria)",
  "🇦🇹 Marko Arnautović (Austria)",
  "🇦🇹 Michael Gregoritsch (Austria)",
  "🇦🇹 Marcel Sabitzer (Austria)",
  "🇦🇹 Christoph Baumgartner (Austria)",
  "🇦🇹 Konrad Laimer (Austria)",
  "🇦🇹 Romano Schmid (Austria)",
  "🇦🇹 Patrick Wimmer (Austria)",
  "🇦🇹 Andreas Weimann (Austria)",
  "🇯🇴 Mousa Al-Taamari (Jordan)",
  "🇯🇴 Yazan Al-Naimat (Jordan)",
  "🇯🇴 Ali Olwan (Jordan)",
  "🇯🇴 Mahmoud Al-Mardi (Jordan)",
  "🇯🇴 Nizar Al-Rashdan (Jordan)",
  "🇯🇴 Noor Al-Rawabdeh (Jordan)",
  "🇯🇴 Ibrahim Sadeh (Jordan)",
  "🇯🇴 Hamza Al-Dardour (Jordan)",
  "🇵🇹 Cristiano Ronaldo (Portugal)",
  "🇵🇹 Rafael Leão (Portugal)",
  "🇵🇹 Bruno Fernandes (Portugal)",
  "🇵🇹 Bernardo Silva (Portugal)",
  "🇵🇹 Gonçalo Ramos (Portugal)",
  "🇵🇹 João Félix (Portugal)",
  "🇵🇹 Diogo Jota (Portugal)",
  "🇵🇹 Pedro Neto (Portugal)",
  "🇵🇹 Francisco Conceição (Portugal)",
  "🇨🇩 Cédric Bakambu (DR Congo)",
  "🇨🇩 Yoane Wissa (DR Congo)",
  "🇨🇩 Silas Katompa Mvumpa (DR Congo)",
  "🇨🇩 Théo Bongonda (DR Congo)",
  "🇨🇩 Simon Banza (DR Congo)",
  "🇨🇩 Meschack Elia (DR Congo)",
  "🇨🇩 Gaël Kakuta (DR Congo)",
  "🇨🇩 Fiston Mayele (DR Congo)",
  "🇨🇴 Luis Díaz (Colombia)",
  "🇨🇴 James Rodríguez (Colombia)",
  "🇨🇴 Jhon Durán (Colombia)",
  "🇨🇴 Rafael Santos Borré (Colombia)",
  "🇨🇴 Jhon Arias (Colombia)",
  "🇨🇴 Luis Sinisterra (Colombia)",
  "🇨🇴 Juan Fernando Quintero (Colombia)",
  "🇨🇴 Miguel Borja (Colombia)",
  "🇺🇿 Eldor Shomurodov (Uzbekistan)",
  "🇺🇿 Abbosbek Fayzullaev (Uzbekistan)",
  "🇺🇿 Jaloliddin Masharipov (Uzbekistan)",
  "🇺🇿 Oston Urunov (Uzbekistan)",
  "🇺🇿 Igor Sergeev (Uzbekistan)",
  "🇺🇿 Azizbek Turgunboev (Uzbekistan)",
  "🇺🇿 Khojimat Erkinov (Uzbekistan)",
  "🇺🇿 Odiljon Hamrobekov (Uzbekistan)",
  "🏴 Harry Kane (England)",
  "🏴 Jude Bellingham (England)",
  "🏴 Bukayo Saka (England)",
  "🏴 Phil Foden (England)",
  "🏴 Cole Palmer (England)",
  "🏴 Marcus Rashford (England)",
  "🏴 Ollie Watkins (England)",
  "🏴 Ivan Toney (England)",
  "🏴 Anthony Gordon (England)",
  "🇭🇷 Andrej Kramarić (Croatia)",
  "🇭🇷 Bruno Petković (Croatia)",
  "🇭🇷 Luka Modrić (Croatia)",
  "🇭🇷 Ivan Perišić (Croatia)",
  "🇭🇷 Mario Pašalić (Croatia)",
  "🇭🇷 Lovro Majer (Croatia)",
  "🇭🇷 Ante Budimir (Croatia)",
  "🇭🇷 Martin Baturina (Croatia)",
  "🇬🇭 Mohammed Kudus (Ghana)",
  "🇬🇭 Jordan Ayew (Ghana)",
  "🇬🇭 Iñaki Williams (Ghana)",
  "🇬🇭 Antoine Semenyo (Ghana)",
  "🇬🇭 Ernest Nuamah (Ghana)",
  "🇬🇭 Kamaldeen Sulemana (Ghana)",
  "🇬🇭 Thomas Partey (Ghana)",
  "🇬🇭 André Ayew (Ghana)",
  "🇵🇦 José Fajardo (Panama)",
  "🇵🇦 Cecilio Waterman (Panama)",
  "🇵🇦 Édgar Bárcenas (Panama)",
  "🇵🇦 Ismael Díaz (Panama)",
  "🇵🇦 Yoel Bárcenas (Panama)",
  "🇵🇦 Alberto Quintero (Panama)",
  "🇵🇦 César Yanis (Panama)",
  "🇵🇦 José Luis Rodríguez (Panama)"
];
