export const groups = [
  { name: "Gruppo A", teams: ["🇲🇽 Mexico", "🇿🇦 South Africa", "🇰🇷 South Korea", "🇨🇿 Czechia"] },
  { name: "Gruppo B", teams: ["🇨🇦 Canada", "🇧🇦 Bosnia and Herzegovina", "🇶🇦 Qatar", "🇨🇭 Switzerland"] },
  { name: "Gruppo C", teams: ["🇧🇷 Brazil", "🇭🇹 Haiti", "🇲🇦 Morocco", "🏴 Scotland"] },
  { name: "Gruppo D", teams: ["🇺🇸 United States", "🇦🇺 Australia", "🇵🇾 Paraguay", "🇹🇷 Türkiye"] },
  { name: "Gruppo E", teams: ["🇨🇼 Curaçao", "🇪🇨 Ecuador", "🇩🇪 Germany", "🇨🇮 Ivory Coast"] },
  { name: "Gruppo F", teams: ["🇳🇱 Netherlands", "🇯🇵 Japan", "🇸🇪 Sweden", "🇹🇳 Tunisia"] },
  { name: "Gruppo G", teams: ["🇧🇪 Belgium", "🇪🇬 Egypt", "🇮🇷 Iran", "🇳🇿 New Zealand"] },
  { name: "Gruppo H", teams: ["🇨🇻 Cape Verde", "🇸🇦 Saudi Arabia", "🇪🇸 Spain", "🇺🇾 Uruguay"] },
  { name: "Gruppo I", teams: ["🇫🇷 France", "🇳🇴 Norway", "🇸🇳 Senegal", "🇮🇶 Iraq"] },
  { name: "Gruppo J", teams: ["🇦🇷 Argentina", "🇩🇿 Algeria", "🇦🇹 Austria", "🇯🇴 Jordan"] },
  { name: "Gruppo K", teams: ["🇵🇹 Portugal", "🇨🇩 DR Congo", "🇨🇴 Colombia", "🇺🇿 Uzbekistan"] },
  { name: "Gruppo L", teams: ["🏴 England", "🇭🇷 Croatia", "🇬🇭 Ghana", "🇵🇦 Panama"] },
];

export const matches = [
  // Gruppo A — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m1", group: "Gruppo A", date: "2026-06-11", kickoff: "2026-06-11T22:00:00+03:00", home: "🇲🇽 Mexico", away: "🇿🇦 South Africa" },
  { id: "m2", group: "Gruppo A", date: "2026-06-12", kickoff: "2026-06-12T05:00:00+03:00", home: "🇰🇷 South Korea", away: "🇨🇿 Czechia" },
  { id: "m3", group: "Gruppo A", date: "2026-06-19", kickoff: "2026-06-19T04:00:00+03:00", home: "🇲🇽 Mexico", away: "🇰🇷 South Korea" },
  { id: "m4", group: "Gruppo A", date: "2026-06-18", kickoff: "2026-06-18T19:00:00+03:00", home: "🇨🇿 Czechia", away: "🇿🇦 South Africa" },
  { id: "m5", group: "Gruppo A", date: "2026-06-25", kickoff: "2026-06-25T04:00:00+03:00", home: "🇨🇿 Czechia", away: "🇲🇽 Mexico" },
  { id: "m6", group: "Gruppo A", date: "2026-06-25", kickoff: "2026-06-25T04:00:00+03:00", home: "🇿🇦 South Africa", away: "🇰🇷 South Korea" },

  // Gruppo B — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m7", group: "Gruppo B", date: "2026-06-12", kickoff: "2026-06-12T22:00:00+03:00", home: "🇨🇦 Canada", away: "🇧🇦 Bosnia and Herzegovina" },
  { id: "m8", group: "Gruppo B", date: "2026-06-13", kickoff: "2026-06-13T22:00:00+03:00", home: "🇶🇦 Qatar", away: "🇨🇭 Switzerland" },
  { id: "m9", group: "Gruppo B", date: "2026-06-19", kickoff: "2026-06-19T01:00:00+03:00", home: "🇨🇦 Canada", away: "🇶🇦 Qatar" },
  { id: "m10", group: "Gruppo B", date: "2026-06-18", kickoff: "2026-06-18T22:00:00+03:00", home: "🇨🇭 Switzerland", away: "🇧🇦 Bosnia and Herzegovina" },
  { id: "m11", group: "Gruppo B", date: "2026-06-24", kickoff: "2026-06-24T22:00:00+03:00", home: "🇨🇭 Switzerland", away: "🇨🇦 Canada" },
  { id: "m12", group: "Gruppo B", date: "2026-06-24", kickoff: "2026-06-24T22:00:00+03:00", home: "🇧🇦 Bosnia and Herzegovina", away: "🇶🇦 Qatar" },

  // Gruppo C — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m13", group: "Gruppo C", date: "2026-06-20", kickoff: "2026-06-20T03:30:00+03:00", home: "🇧🇷 Brazil", away: "🇭🇹 Haiti" },
  { id: "m14", group: "Gruppo C", date: "2026-06-20", kickoff: "2026-06-20T01:00:00+03:00", home: "🇲🇦 Morocco", away: "🏴 Scotland" },
  { id: "m15", group: "Gruppo C", date: "2026-06-14", kickoff: "2026-06-14T01:00:00+03:00", home: "🇧🇷 Brazil", away: "🇲🇦 Morocco" },
  { id: "m16", group: "Gruppo C", date: "2026-06-14", kickoff: "2026-06-14T04:00:00+03:00", home: "🏴 Scotland", away: "🇭🇹 Haiti" },
  { id: "m17", group: "Gruppo C", date: "2026-06-25", kickoff: "2026-06-25T01:00:00+03:00", home: "🏴 Scotland", away: "🇧🇷 Brazil" },
  { id: "m18", group: "Gruppo C", date: "2026-06-25", kickoff: "2026-06-25T01:00:00+03:00", home: "🇭🇹 Haiti", away: "🇲🇦 Morocco" },

 // Gruppo D — Romania time saved as +03:00; browser converts automatically for other countries
{ id: "m19", group: "Gruppo D", date: "2026-06-13", kickoff: "2026-06-13T04:00:00+03:00", home: "🇺🇸 United States", away: "🇵🇾 Paraguay" },
{ id: "m20", group: "Gruppo D", date: "2026-06-14", kickoff: "2026-06-14T21:00:00+03:00", home: "🇦🇺 Australia", away: "🇹🇷 Türkiye" },
{ id: "m21", group: "Gruppo D", date: "2026-06-20", kickoff: "2026-06-20T06:00:00+03:00", home: "🇺🇸 United States", away: "🇦🇺 Australia" },
{ id: "m22", group: "Gruppo D", date: "2026-06-20", kickoff: "2026-06-20T22:00:00+03:00", home: "🇹🇷 Türkiye", away: "🇵🇾 Paraguay" },
{ id: "m23", group: "Gruppo D", date: "2026-06-26", kickoff: "2026-06-26T05:00:00+03:00", home: "🇹🇷 Türkiye", away: "🇺🇸 United States" },
{ id: "m24", group: "Gruppo D", date: "2026-06-26", kickoff: "2026-06-26T05:00:00+03:00", home: "🇦🇺 Australia", away: "🇵🇾 Paraguay" },

  // Gruppo E — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m25", group: "Gruppo E", date: "2026-06-21", kickoff: "2026-06-21T03:00:00+03:00", home: "🇨🇼 Curaçao", away: "🇪🇨 Ecuador" },
  { id: "m26", group: "Gruppo E", date: "2026-06-20", kickoff: "2026-06-20T23:00:00+03:00", home: "🇩🇪 Germany", away: "🇨🇮 Ivory Coast" },
  { id: "m27", group: "Gruppo E", date: "2026-06-14", kickoff: "2026-06-14T20:00:00+03:00", home: "🇨🇼 Curaçao", away: "🇩🇪 Germany" },
  { id: "m28", group: "Gruppo E", date: "2026-06-15", kickoff: "2026-06-15T02:00:00+03:00", home: "🇨🇮 Ivory Coast", away: "🇪🇨 Ecuador" },
  { id: "m29", group: "Gruppo E", date: "2026-06-25", kickoff: "2026-06-25T23:00:00+03:00", home: "🇨🇮 Ivory Coast", away: "🇨🇼 Curaçao" },
  { id: "m30", group: "Gruppo E", date: "2026-06-25", kickoff: "2026-06-25T23:00:00+03:00", home: "🇪🇨 Ecuador", away: "🇩🇪 Germany" },

  // Gruppo F — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m31", group: "Gruppo F", date: "2026-06-14", kickoff: "2026-06-14T23:00:00+03:00", home: "🇳🇱 Netherlands", away: "🇯🇵 Japan" },
  { id: "m32", group: "Gruppo F", date: "2026-06-15", kickoff: "2026-06-15T05:00:00+03:00", home: "🇸🇪 Sweden", away: "🇹🇳 Tunisia" },
  { id: "m33", group: "Gruppo F", date: "2026-06-20", kickoff: "2026-06-20T20:00:00+03:00", home: "🇳🇱 Netherlands", away: "🇸🇪 Sweden" },
  { id: "m34", group: "Gruppo F", date: "2026-06-21", kickoff: "2026-06-21T07:00:00+03:00", home: "🇹🇳 Tunisia", away: "🇯🇵 Japan" },
  { id: "m35", group: "Gruppo F", date: "2026-06-26", kickoff: "2026-06-26T02:00:00+03:00", home: "🇹🇳 Tunisia", away: "🇳🇱 Netherlands" },
  { id: "m36", group: "Gruppo F", date: "2026-06-26", kickoff: "2026-06-26T02:00:00+03:00", home: "🇯🇵 Japan", away: "🇸🇪 Sweden" },

  // Gruppo G — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m37", group: "Gruppo G", date: "2026-06-15", kickoff: "2026-06-15T22:00:00+03:00", home: "🇧🇪 Belgium", away: "🇪🇬 Egypt" },
  { id: "m38", group: "Gruppo G", date: "2026-06-16", kickoff: "2026-06-16T04:00:00+03:00", home: "🇮🇷 Iran", away: "🇳🇿 New Zealand" },
  { id: "m39", group: "Gruppo G", date: "2026-06-21", kickoff: "2026-06-21T22:00:00+03:00", home: "🇧🇪 Belgium", away: "🇮🇷 Iran" },
  { id: "m40", group: "Gruppo G", date: "2026-06-22", kickoff: "2026-06-22T04:00:00+03:00", home: "🇳🇿 New Zealand", away: "🇪🇬 Egypt" },
  { id: "m41", group: "Gruppo G", date: "2026-06-27", kickoff: "2026-06-27T06:00:00+03:00", home: "🇳🇿 New Zealand", away: "🇧🇪 Belgium" },
  { id: "m42", group: "Gruppo G", date: "2026-06-27", kickoff: "2026-06-27T06:00:00+03:00", home: "🇪🇬 Egypt", away: "🇮🇷 Iran" },

  // Gruppo H — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m43", group: "Gruppo H", date: "2026-06-27", kickoff: "2026-06-27T03:00:00+03:00", home: "🇨🇻 Cape Verde", away: "🇸🇦 Saudi Arabia" },
  { id: "m44", group: "Gruppo H", date: "2026-06-27", kickoff: "2026-06-27T03:00:00+03:00", home: "🇪🇸 Spain", away: "🇺🇾 Uruguay" },
  { id: "m45", group: "Gruppo H", date: "2026-06-15", kickoff: "2026-06-15T19:00:00+03:00", home: "🇨🇻 Cape Verde", away: "🇪🇸 Spain" },
  { id: "m46", group: "Gruppo H", date: "2026-06-16", kickoff: "2026-06-16T01:00:00+03:00", home: "🇺🇾 Uruguay", away: "🇸🇦 Saudi Arabia" },
  { id: "m47", group: "Gruppo H", date: "2026-06-22", kickoff: "2026-06-22T01:00:00+03:00", home: "🇺🇾 Uruguay", away: "🇨🇻 Cape Verde" },
  { id: "m48", group: "Gruppo H", date: "2026-06-21", kickoff: "2026-06-21T19:00:00+03:00", home: "🇸🇦 Saudi Arabia", away: "🇪🇸 Spain" },

  // Gruppo I — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m49", group: "Gruppo I", date: "2026-06-26", kickoff: "2026-06-26T22:00:00+03:00", home: "🇫🇷 France", away: "🇳🇴 Norway" },
  { id: "m50", group: "Gruppo I", date: "2026-06-26", kickoff: "2026-06-26T22:00:00+03:00", home: "🇸🇳 Senegal", away: "🇮🇶 Iraq" },
  { id: "m51", group: "Gruppo I", date: "2026-06-16", kickoff: "2026-06-16T22:00:00+03:00", home: "🇫🇷 France", away: "🇸🇳 Senegal" },
  { id: "m52", group: "Gruppo I", date: "2026-06-17", kickoff: "2026-06-17T01:00:00+03:00", home: "🇮🇶 Iraq", away: "🇳🇴 Norway" },
  { id: "m53", group: "Gruppo I", date: "2026-06-23", kickoff: "2026-06-23T00:00:00+03:00", home: "🇮🇶 Iraq", away: "🇫🇷 France" },
  { id: "m54", group: "Gruppo I", date: "2026-06-23", kickoff: "2026-06-23T03:00:00+03:00", home: "🇳🇴 Norway", away: "🇸🇳 Senegal" },

  // Gruppo J — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m55", group: "Gruppo J", date: "2026-06-17", kickoff: "2026-06-17T04:00:00+03:00", home: "🇦🇷 Argentina", away: "🇩🇿 Algeria" },
  { id: "m56", group: "Gruppo J", date: "2026-06-17", kickoff: "2026-06-17T07:00:00+03:00", home: "🇦🇹 Austria", away: "🇯🇴 Jordan" },
  { id: "m57", group: "Gruppo J", date: "2026-06-22", kickoff: "2026-06-22T20:00:00+03:00", home: "🇦🇷 Argentina", away: "🇦🇹 Austria" },
  { id: "m58", group: "Gruppo J", date: "2026-06-23", kickoff: "2026-06-23T06:00:00+03:00", home: "🇯🇴 Jordan", away: "🇩🇿 Algeria" },
  { id: "m59", group: "Gruppo J", date: "2026-06-28", kickoff: "2026-06-28T05:00:00+03:00", home: "🇯🇴 Jordan", away: "🇦🇷 Argentina" },
  { id: "m60", group: "Gruppo J", date: "2026-06-28", kickoff: "2026-06-28T05:00:00+03:00", home: "🇩🇿 Algeria", away: "🇦🇹 Austria" },

  // Gruppo K — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m61", group: "Gruppo K", date: "2026-06-17", kickoff: "2026-06-17T20:00:00+03:00", home: "🇵🇹 Portugal", away: "🇨🇩 DR Congo" },
  { id: "m62", group: "Gruppo K", date: "2026-06-18", kickoff: "2026-06-18T05:00:00+03:00", home: "🇨🇴 Colombia", away: "🇺🇿 Uzbekistan" },
  { id: "m63", group: "Gruppo K", date: "2026-06-28", kickoff: "2026-06-28T02:30:00+03:00", home: "🇵🇹 Portugal", away: "🇨🇴 Colombia" },
  { id: "m64", group: "Gruppo K", date: "2026-06-28", kickoff: "2026-06-28T02:30:00+03:00", home: "🇺🇿 Uzbekistan", away: "🇨🇩 DR Congo" },
  { id: "m65", group: "Gruppo K", date: "2026-06-23", kickoff: "2026-06-23T20:00:00+03:00", home: "🇺🇿 Uzbekistan", away: "🇵🇹 Portugal" },
  { id: "m66", group: "Gruppo K", date: "2026-06-24", kickoff: "2026-06-24T05:00:00+03:00", home: "🇨🇩 DR Congo", away: "🇨🇴 Colombia" },

  // Gruppo L — Romania time saved as +03:00; browser converts automatically for other countries
  { id: "m67", group: "Gruppo L", date: "2026-06-17", kickoff: "2026-06-17T23:00:00+03:00", home: "🏴 England", away: "🇭🇷 Croatia" },
  { id: "m68", group: "Gruppo L", date: "2026-06-18", kickoff: "2026-06-18T02:00:00+03:00", home: "🇬🇭 Ghana", away: "🇵🇦 Panama" },
  { id: "m69", group: "Gruppo L", date: "2026-06-23", kickoff: "2026-06-23T23:00:00+03:00", home: "🏴 England", away: "🇬🇭 Ghana" },
  { id: "m70", group: "Gruppo L", date: "2026-06-24", kickoff: "2026-06-24T02:00:00+03:00", home: "🇵🇦 Panama", away: "🇭🇷 Croatia" },
  { id: "m71", group: "Gruppo L", date: "2026-06-28", kickoff: "2026-06-28T00:00:00+03:00", home: "🇵🇦 Panama", away: "🏴 England" },
  { id: "m72", group: "Gruppo L", date: "2026-06-28", kickoff: "2026-06-28T00:00:00+03:00", home: "🇭🇷 Croatia", away: "🇬🇭 Ghana" },

];

export const knockoutRounds = [
  {
    round: "Sedicesimi",
    matches: [
      "2A - 2B",          // FIFA Match 73
      "1E - 3ABCDF",      // FIFA Match 74
      "1F - 2C",          // FIFA Match 75
      "1C - 2F",          // FIFA Match 76
      "1I - 3CDFGH",      // FIFA Match 77
      "2E - 2I",          // FIFA Match 78
      "1A - 3CEFHI",      // FIFA Match 79
      "1L - 3EHIJK",      // FIFA Match 80
      "1D - 3BEFIJ",      // FIFA Match 81
      "1G - 3AEHIJ",      // FIFA Match 82
      "2K - 2L",          // FIFA Match 83
      "1H - 2J",          // FIFA Match 84
      "1B - 3EFGIJ",      // FIFA Match 85
      "1J - 2H",          // FIFA Match 86
      "1K - 3DEIJL",      // FIFA Match 87
      "2D - 2G",          // FIFA Match 88
    ],
  },
  {
    round: "Ottavi",
    matches: [
      "Vincente S2 - Vincente S5",    // FIFA Match 89: W74 vs W77
      "Vincente S1 - Vincente S3",    // FIFA Match 90: W73 vs W75
      "Vincente S4 - Vincente S6",    // FIFA Match 91: W76 vs W78
      "Vincente S7 - Vincente S8",    // FIFA Match 92: W79 vs W80
      "Vincente S11 - Vincente S12",  // FIFA Match 93: W83 vs W84
      "Vincente S9 - Vincente S10",   // FIFA Match 94: W81 vs W82
      "Vincente S14 - Vincente S16",  // FIFA Match 95: W86 vs W88
      "Vincente S13 - Vincente S15",  // FIFA Match 96: W85 vs W87
    ],
  },
  {
    round: "Quarti",
    matches: [
      "Vincente O1 - Vincente O2",    // FIFA Match 97: W89 vs W90
      "Vincente O5 - Vincente O6",    // FIFA Match 98: W93 vs W94
      "Vincente O3 - Vincente O4",    // FIFA Match 99: W91 vs W92
      "Vincente O7 - Vincente O8",    // FIFA Match 100: W95 vs W96
    ],
  },
  {
    round: "Semifinali",
    matches: [
      "Vincente Q1 - Vincente Q2",    // FIFA Match 101: W97 vs W98
      "Vincente Q3 - Vincente Q4",    // FIFA Match 102: W99 vs W100
    ],
  },
  {
    round: "Finale 3° posto",
    matches: [
      "Perdente SF1 - Perdente SF2",  // FIFA Match 103
    ],
  },
  {
    round: "Finale",
    matches: [
      "Vincente SF1 - Vincente SF2",  // FIFA Match 104
    ],
  },
];

export const topScorers = [
  "🇲🇽 Santiago Giménez (Mexico)",
  "🇲🇽 Raúl Jiménez (Mexico)",
  "🇲🇽 Hirving Lozano (Mexico)",
  "🇲🇽 Henry Martín (Mexico)",
  "🇲🇽 Uriel Antuna (Mexico)",
  "🇲🇽 Julián Quiñones (Mexico)",
  "🇲🇽 Roberto Alvarado (Mexico)",
  "🇲🇽 Alexis Vega (Mexico)",
  "🇿🇦 Percy Tau (South Africa)",
  "🇿🇦 Lyle Foster (South Africa)",
  "🇿🇦 Evidence Makgopa (South Africa)",
  "🇿🇦 Themba Zwane (South Africa)",
  "🇿🇦 Zakhele Lepasa (South Africa)",
  "🇿🇦 Iqraam Rayners (South Africa)",
  "🇿🇦 Oswin Appollis (South Africa)",
  "🇿🇦 Teboho Mokoena (South Africa)",
  "🇰🇷 Son Heung-min (South Korea)",
  "🇰🇷 Hwang Hee-chan (South Korea)",
  "🇰🇷 Lee Kang-in (South Korea)",
  "🇰🇷 Cho Gue-sung (South Korea)",
  "🇰🇷 Oh Hyeon-gyu (South Korea)",
  "🇰🇷 Hwang Ui-jo (South Korea)",
  "🇰🇷 Jeong Woo-yeong (South Korea)",
  "🇰🇷 Hong Hyun-seok (South Korea)",
  "🇨🇿 Patrik Schick (Czechia)",
  "🇨🇿 Adam Hložek (Czechia)",
  "🇨🇿 Tomáš Čvančara (Czechia)",
  "🇨🇿 Mojmír Chytil (Czechia)",
  "🇨🇿 Václav Černý (Czechia)",
  "🇨🇿 Lukáš Provod (Czechia)",
  "🇨🇿 Jan Kuchta (Czechia)",
  "🇨🇿 Antonín Barák (Czechia)",
  "🇨🇦 Jonathan David (Canada)",
  "🇨🇦 Alphonso Davies (Canada)",
  "🇨🇦 Cyle Larin (Canada)",
  "🇨🇦 Tajon Buchanan (Canada)",
  "🇨🇦 Jacob Shaffelburg (Canada)",
  "🇨🇦 Ismaël Koné (Canada)",
  "🇨🇦 Jonathan Osorio (Canada)",
  "🇨🇦 Liam Millar (Canada)",
  "🇧🇦 Edin Džeko (Bosnia and Herzegovina)",
  "🇧🇦 Ermedin Demirović (Bosnia and Herzegovina)",
  "🇧🇦 Haris Tabaković (Bosnia and Herzegovina)",
  "🇧🇦 Smail Prevljak (Bosnia and Herzegovina)",
  "🇧🇦 Benjamin Tahirović (Bosnia and Herzegovina)",
  "🇧🇦 Amar Dedić (Bosnia and Herzegovina)",
  "🇧🇦 Rade Krunić (Bosnia and Herzegovina)",
  "🇧🇦 Denis Huseinbašić (Bosnia and Herzegovina)",
  "🇶🇦 Akram Afif (Qatar)",
  "🇶🇦 Almoez Ali (Qatar)",
  "🇶🇦 Hassan Al-Haydos (Qatar)",
  "🇶🇦 Mohammed Muntari (Qatar)",
  "🇶🇦 Ahmed Alaaeldin (Qatar)",
  "🇶🇦 Yusuf Abdurisag (Qatar)",
  "🇶🇦 Assim Madibo (Qatar)",
  "🇶🇦 Abdulaziz Hatem (Qatar)",
  "🇨🇭 Breel Embolo (Switzerland)",
  "🇨🇭 Noah Okafor (Switzerland)",
  "🇨🇭 Zeki Amdouni (Switzerland)",
  "🇨🇭 Xherdan Shaqiri (Switzerland)",
  "🇨🇭 Ruben Vargas (Switzerland)",
  "🇨🇭 Dan Ndoye (Switzerland)",
  "🇨🇭 Renato Steffen (Switzerland)",
  "🇨🇭 Granit Xhaka (Switzerland)",
  "🇧🇷 Vinícius Jr (Brazil)",
  "🇧🇷 Rodrygo (Brazil)",
  "🇧🇷 Endrick (Brazil)",
  "🇧🇷 Raphinha (Brazil)",
  "🇧🇷 Gabriel Martinelli (Brazil)",
  "🇧🇷 Richarlison (Brazil)",
  "🇧🇷 Gabriel Jesus (Brazil)",
  "🇧🇷 Neymar (Brazil)",
  "🇧🇷 Lucas Paquetá (Brazil)",
  "🇧🇷 Bruno Guimarães (Brazil)",
  "🇭🇹 Duckens Nazon (Haiti)",
  "🇭🇹 Frantzdy Pierrot (Haiti)",
  "🇭🇹 Fafà Picault (Haiti)",
  "🇭🇹 Carnejy Antoine (Haiti)",
  "🇭🇹 Leverton Pierre (Haiti)",
  "🇭🇹 Derrick Etienne Jr (Haiti)",
  "🇭🇹 Danley Jean Jacques (Haiti)",
  "🇭🇹 Louicius Don Deedson (Haiti)",
  "🇲🇦 Youssef En-Nesyri (Morocco)",
  "🇲🇦 Achraf Hakimi (Morocco)",
  "🇲🇦 Hakim Ziyech (Morocco)",
  "🇲🇦 Sofiane Boufal (Morocco)",
  "🇲🇦 Amine Adli (Morocco)",
  "🇲🇦 Ayoub El Kaabi (Morocco)",
  "🇲🇦 Brahim Díaz (Morocco)",
  "🇲🇦 Soufiane Rahimi (Morocco)",
  "🇲🇦 Azzedine Ounahi (Morocco)",
  "🏴 Scott McTominay (Scotland)",
  "🏴 Che Adams (Scotland)",
  "🏴 Lyndon Dykes (Scotland)",
  "🏴 John McGinn (Scotland)",
  "🏴 Ryan Christie (Scotland)",
  "🏴 Lawrence Shankland (Scotland)",
  "🏴 Ben Doak (Scotland)",
  "🏴 Billy Gilmour (Scotland)",
  "🇺🇸 Christian Pulisic (United States)",
  "🇺🇸 Folarin Balogun (United States)",
  "🇺🇸 Timothy Weah (United States)",
  "🇺🇸 Giovanni Reyna (United States)",
  "🇺🇸 Ricardo Pepi (United States)",
  "🇺🇸 Brenden Aaronson (United States)",
  "🇺🇸 Haji Wright (United States)",
  "🇺🇸 Weston McKennie (United States)",
  "🇦🇺 Mitchell Duke (Australia)",
  "🇦🇺 Craig Goodwin (Australia)",
  "🇦🇺 Mathew Leckie (Australia)",
  "🇦🇺 Riley McGree (Australia)",
  "🇦🇺 Jackson Irvine (Australia)",
  "🇦🇺 Brandon Borrello (Australia)",
  "🇦🇺 Kusini Yengi (Australia)",
  "🇦🇺 Martin Boyle (Australia)",
  "🇵🇾 Miguel Almirón (Paraguay)",
  "🇵🇾 Julio Enciso (Paraguay)",
  "🇵🇾 Ramón Sosa (Paraguay)",
  "🇵🇾 Antonio Sanabria (Paraguay)",
  "🇵🇾 Gabriel Ávalos (Paraguay)",
  "🇵🇾 Matías Rojas (Paraguay)",
  "🇵🇾 Ángel Romero (Paraguay)",
  "🇵🇾 Adam Bareiro (Paraguay)",
  "🇹🇷 Hakan Çalhanoğlu (Türkiye)",
  "🇹🇷 Arda Güler (Türkiye)",
  "🇹🇷 Kerem Aktürkoğlu (Türkiye)",
  "🇹🇷 Cenk Tosun (Türkiye)",
  "🇹🇷 Barış Alper Yılmaz (Türkiye)",
  "🇹🇷 Yunus Akgün (Türkiye)",
  "🇹🇷 İrfan Can Kahveci (Türkiye)",
  "🇹🇷 Semih Kılıçsoy (Türkiye)",
  "🇨🇼 Leandro Bacuna (Curaçao)",
  "🇨🇼 Juninho Bacuna (Curaçao)",
  "🇨🇼 Jearl Margaritha (Curaçao)",
  "🇨🇼 Rangelo Janga (Curaçao)",
  "🇨🇼 Brandley Kuwas (Curaçao)",
  "🇨🇼 Gervane Kastaneer (Curaçao)",
  "🇨🇼 Jeremy Antonisse (Curaçao)",
  "🇨🇼 Kenji Gorré (Curaçao)",
  "🇪🇨 Enner Valencia (Ecuador)",
  "🇪🇨 Moisés Caicedo (Ecuador)",
  "🇪🇨 Piero Hincapié (Ecuador)",
  "🇪🇨 Kendry Páez (Ecuador)",
  "🇪🇨 Kevin Rodríguez (Ecuador)",
  "🇪🇨 Gonzalo Plata (Ecuador)",
  "🇪🇨 Ángel Mena (Ecuador)",
  "🇪🇨 Jeremy Sarmiento (Ecuador)",
  "🇩🇪 Florian Wirtz (Germany)",
  "🇩🇪 Kai Havertz (Germany)",
  "🇩🇪 Jamal Musiala (Germany)",
  "🇩🇪 Niclas Füllkrug (Germany)",
  "🇩🇪 Serge Gnabry (Germany)",
  "🇩🇪 Leroy Sané (Germany)",
  "🇩🇪 Thomas Müller (Germany)",
  "🇩🇪 Maximilian Beier (Germany)",
  "🇩🇪 Deniz Undav (Germany)",
  "🇨🇮 Sébastien Haller (Ivory Coast)",
  "🇨🇮 Simon Adingra (Ivory Coast)",
  "🇨🇮 Nicolas Pépé (Ivory Coast)",
  "🇨🇮 Wilfried Zaha (Ivory Coast)",
  "🇨🇮 Franck Kessié (Ivory Coast)",
  "🇨🇮 Oumar Diakité (Ivory Coast)",
  "🇨🇮 Karim Konaté (Ivory Coast)",
  "🇨🇮 Jean-Philippe Krasso (Ivory Coast)",
  "🇳🇱 Cody Gakpo (Netherlands)",
  "🇳🇱 Memphis Depay (Netherlands)",
  "🇳🇱 Xavi Simons (Netherlands)",
  "🇳🇱 Donyell Malen (Netherlands)",
  "🇳🇱 Brian Brobbey (Netherlands)",
  "🇳🇱 Wout Weghorst (Netherlands)",
  "🇳🇱 Steven Bergwijn (Netherlands)",
  "🇳🇱 Tijjani Reijnders (Netherlands)",
  "🇯🇵 Takefusa Kubo (Japan)",
  "🇯🇵 Kaoru Mitoma (Japan)",
  "🇯🇵 Takumi Minamino (Japan)",
  "🇯🇵 Daichi Kamada (Japan)",
  "🇯🇵 Ritsu Doan (Japan)",
  "🇯🇵 Ayase Ueda (Japan)",
  "🇯🇵 Kyogo Furuhashi (Japan)",
  "🇯🇵 Daizen Maeda (Japan)",
  "🇯🇵 Junya Ito (Japan)",
  "🇸🇪 Alexander Isak (Sweden)",
  "🇸🇪 Viktor Gyökeres (Sweden)",
  "🇸🇪 Dejan Kulusevski (Sweden)",
  "🇸🇪 Anthony Elanga (Sweden)",
  "🇸🇪 Emil Forsberg (Sweden)",
  "🇸🇪 Jesper Karlsson (Sweden)",
  "🇸🇪 Robin Quaison (Sweden)",
  "🇸🇪 Mattias Svanberg (Sweden)",
  "🇹🇳 Youssef Msakni (Tunisia)",
  "🇹🇳 Wahbi Khazri (Tunisia)",
  "🇹🇳 Hannibal Mejbri (Tunisia)",
  "🇹🇳 Elias Achouri (Tunisia)",
  "🇹🇳 Seifeddine Jaziri (Tunisia)",
  "🇹🇳 Haythem Jouini (Tunisia)",
  "🇹🇳 Ali Abdi (Tunisia)",
  "🇹🇳 Anis Ben Slimane (Tunisia)",
  "🇧🇪 Romelu Lukaku (Belgium)",
  "🇧🇪 Kevin De Bruyne (Belgium)",
  "🇧🇪 Jérémy Doku (Belgium)",
  "🇧🇪 Leandro Trossard (Belgium)",
  "🇧🇪 Loïs Openda (Belgium)",
  "🇧🇪 Charles De Ketelaere (Belgium)",
  "🇧🇪 Dodi Lukebakio (Belgium)",
  "🇧🇪 Youri Tielemans (Belgium)",
  "🇪🇬 Mohamed Salah (Egypt)",
  "🇪🇬 Mostafa Mohamed (Egypt)",
  "🇪🇬 Omar Marmoush (Egypt)",
  "🇪🇬 Trézéguet (Egypt)",
  "🇪🇬 Zizo (Egypt)",
  "🇪🇬 Emam Ashour (Egypt)",
  "🇪🇬 Mahmoud Kahraba (Egypt)",
  "🇪🇬 Ibrahim Adel (Egypt)",
  "🇮🇷 Mehdi Taremi (Iran)",
  "🇮🇷 Sardar Azmoun (Iran)",
  "🇮🇷 Alireza Jahanbakhsh (Iran)",
  "🇮🇷 Mehdi Ghayedi (Iran)",
  "🇮🇷 Saman Ghoddos (Iran)",
  "🇮🇷 Ali Gholizadeh (Iran)",
  "🇮🇷 Mohammad Mohebi (Iran)",
  "🇮🇷 Karim Ansarifard (Iran)",
  "🇳🇿 Chris Wood (New Zealand)",
  "🇳🇿 Ben Waine (New Zealand)",
  "🇳🇿 Kosta Barbarouses (New Zealand)",
  "🇳🇿 Sarpreet Singh (New Zealand)",
  "🇳🇿 Elijah Just (New Zealand)",
  "🇳🇿 Marco Rojas (New Zealand)",
  "🇳🇿 Callum McCowatt (New Zealand)",
  "🇳🇿 Matthew Garbett (New Zealand)",
  "🇨🇻 Ryan Mendes (Cape Verde)",
  "🇨🇻 Bebé (Cape Verde)",
  "🇨🇻 Jovane Cabral (Cape Verde)",
  "🇨🇻 Garry Rodrigues (Cape Verde)",
  "🇨🇻 Djaniny (Cape Verde)",
  "🇨🇻 Willy Semedo (Cape Verde)",
  "🇨🇻 Jamiro Monteiro (Cape Verde)",
  "🇨🇻 Kevin Pina (Cape Verde)",
  "🇸🇦 Salem Al-Dawsari (Saudi Arabia)",
  "🇸🇦 Firas Al-Buraikan (Saudi Arabia)",
  "🇸🇦 Saleh Al-Shehri (Saudi Arabia)",
  "🇸🇦 Abdulrahman Ghareeb (Saudi Arabia)",
  "🇸🇦 Sami Al-Najei (Saudi Arabia)",
  "🇸🇦 Hattan Bahebri (Saudi Arabia)",
  "🇸🇦 Ayman Yahya (Saudi Arabia)",
  "🇸🇦 Mohammed Kanno (Saudi Arabia)",
  "🇪🇸 Álvaro Morata (Spain)",
  "🇪🇸 Lamine Yamal (Spain)",
  "🇪🇸 Nico Williams (Spain)",
  "🇪🇸 Dani Olmo (Spain)",
  "🇪🇸 Pedri (Spain)",
  "🇪🇸 Mikel Oyarzabal (Spain)",
  "🇪🇸 Ferran Torres (Spain)",
  "🇪🇸 Joselu (Spain)",
  "🇪🇸 Fermín López (Spain)",
  "🇺🇾 Darwin Núñez (Uruguay)",
  "🇺🇾 Federico Valverde (Uruguay)",
  "🇺🇾 Luis Suárez (Uruguay)",
  "🇺🇾 Facundo Pellistri (Uruguay)",
  "🇺🇾 Nicolás de la Cruz (Uruguay)",
  "🇺🇾 Giorgian de Arrascaeta (Uruguay)",
  "🇺🇾 Maximiliano Araújo (Uruguay)",
  "🇺🇾 Brian Rodríguez (Uruguay)",
  "🇫🇷 Kylian Mbappé (France)",
  "🇫🇷 Ousmane Dembélé (France)",
  "🇫🇷 Marcus Thuram (France)",
  "🇫🇷 Randal Kolo Muani (France)",
  "🇫🇷 Bradley Barcola (France)",
  "🇫🇷 Antoine Griezmann (France)",
  "🇫🇷 Kingsley Coman (France)",
  "🇫🇷 Christopher Nkunku (France)",
  "🇫🇷 Olivier Giroud (France)",
  "🇳🇴 Erling Haaland (Norway)",
  "🇳🇴 Martin Ødegaard (Norway)",
  "🇳🇴 Alexander Sørloth (Norway)",
  "🇳🇴 Antonio Nusa (Norway)",
  "🇳🇴 Jørgen Strand Larsen (Norway)",
  "🇳🇴 Oscar Bobb (Norway)",
  "🇳🇴 Sander Berge (Norway)",
  "🇳🇴 Kristian Thorstvedt (Norway)",
  "🇸🇳 Sadio Mané (Senegal)",
  "🇸🇳 Nicolas Jackson (Senegal)",
  "🇸🇳 Ismaïla Sarr (Senegal)",
  "🇸🇳 Habib Diallo (Senegal)",
  "🇸🇳 Boulaye Dia (Senegal)",
  "🇸🇳 Iliman Ndiaye (Senegal)",
  "🇸🇳 Krépin Diatta (Senegal)",
  "🇸🇳 Pape Matar Sarr (Senegal)",
  "🇮🇶 Aymen Hussein (Iraq)",
  "🇮🇶 Ali Al-Hamadi (Iraq)",
  "🇮🇶 Mohanad Ali (Iraq)",
  "🇮🇶 Ibrahim Bayesh (Iraq)",
  "🇮🇶 Amir Al-Ammari (Iraq)",
  "🇮🇶 Bashar Resan (Iraq)",
  "🇮🇶 Hussein Ali (Iraq)",
  "🇮🇶 Youssef Amyn (Iraq)",
  "🇦🇷 Lionel Messi (Argentina)",
  "🇦🇷 Lautaro Martínez (Argentina)",
  "🇦🇷 Julián Álvarez (Argentina)",
  "🇦🇷 Paulo Dybala (Argentina)",
  "🇦🇷 Alejandro Garnacho (Argentina)",
  "🇦🇷 Ángel Di María (Argentina)",
  "🇦🇷 Nicolás González (Argentina)",
  "🇦🇷 Giovanni Simeone (Argentina)",
  "🇦🇷 Thiago Almada (Argentina)",
  "🇩🇿 Riyad Mahrez (Algeria)",
  "🇩🇿 Amine Gouiri (Algeria)",
  "🇩🇿 Islam Slimani (Algeria)",
  "🇩🇿 Youcef Belaïli (Algeria)",
  "🇩🇿 Baghdad Bounedjah (Algeria)",
  "🇩🇿 Saïd Benrahma (Algeria)",
  "🇩🇿 Farès Chaïbi (Algeria)",
  "🇩🇿 Houssem Aouar (Algeria)",
  "🇦🇹 Marko Arnautović (Austria)",
  "🇦🇹 Michael Gregoritsch (Austria)",
  "🇦🇹 Marcel Sabitzer (Austria)",
  "🇦🇹 Christoph Baumgartner (Austria)",
  "🇦🇹 Konrad Laimer (Austria)",
  "🇦🇹 Romano Schmid (Austria)",
  "🇦🇹 Patrick Wimmer (Austria)",
  "🇦🇹 Andreas Weimann (Austria)",
  "🇯🇴 Mousa Al-Taamari (Jordan)",
  "🇯🇴 Yazan Al-Naimat (Jordan)",
  "🇯🇴 Ali Olwan (Jordan)",
  "🇯🇴 Mahmoud Al-Mardi (Jordan)",
  "🇯🇴 Nizar Al-Rashdan (Jordan)",
  "🇯🇴 Noor Al-Rawabdeh (Jordan)",
  "🇯🇴 Ibrahim Sadeh (Jordan)",
  "🇯🇴 Hamza Al-Dardour (Jordan)",
  "🇵🇹 Cristiano Ronaldo (Portugal)",
  "🇵🇹 Rafael Leão (Portugal)",
  "🇵🇹 Bruno Fernandes (Portugal)",
  "🇵🇹 Bernardo Silva (Portugal)",
  "🇵🇹 Gonçalo Ramos (Portugal)",
  "🇵🇹 João Félix (Portugal)",
  "🇵🇹 Diogo Jota (Portugal)",
  "🇵🇹 Pedro Neto (Portugal)",
  "🇵🇹 Francisco Conceição (Portugal)",
  "🇨🇩 Cédric Bakambu (DR Congo)",
  "🇨🇩 Yoane Wissa (DR Congo)",
  "🇨🇩 Silas Katompa Mvumpa (DR Congo)",
  "🇨🇩 Théo Bongonda (DR Congo)",
  "🇨🇩 Simon Banza (DR Congo)",
  "🇨🇩 Meschack Elia (DR Congo)",
  "🇨🇩 Gaël Kakuta (DR Congo)",
  "🇨🇩 Fiston Mayele (DR Congo)",
  "🇨🇴 Luis Díaz (Colombia)",
  "🇨🇴 James Rodríguez (Colombia)",
  "🇨🇴 Jhon Durán (Colombia)",
  "🇨🇴 Rafael Santos Borré (Colombia)",
  "🇨🇴 Jhon Arias (Colombia)",
  "🇨🇴 Luis Sinisterra (Colombia)",
  "🇨🇴 Juan Fernando Quintero (Colombia)",
  "🇨🇴 Miguel Borja (Colombia)",
  "🇺🇿 Eldor Shomurodov (Uzbekistan)",
  "🇺🇿 Abbosbek Fayzullaev (Uzbekistan)",
  "🇺🇿 Jaloliddin Masharipov (Uzbekistan)",
  "🇺🇿 Oston Urunov (Uzbekistan)",
  "🇺🇿 Igor Sergeev (Uzbekistan)",
  "🇺🇿 Azizbek Turgunboev (Uzbekistan)",
  "🇺🇿 Khojimat Erkinov (Uzbekistan)",
  "🇺🇿 Odiljon Hamrobekov (Uzbekistan)",
  "🏴 Harry Kane (England)",
  "🏴 Jude Bellingham (England)",
  "🏴 Bukayo Saka (England)",
  "🏴 Phil Foden (England)",
  "🏴 Cole Palmer (England)",
  "🏴 Marcus Rashford (England)",
  "🏴 Ollie Watkins (England)",
  "🏴 Ivan Toney (England)",
  "🏴 Anthony Gordon (England)",
  "🇭🇷 Andrej Kramarić (Croatia)",
  "🇭🇷 Bruno Petković (Croatia)",
  "🇭🇷 Luka Modrić (Croatia)",
  "🇭🇷 Ivan Perišić (Croatia)",
  "🇭🇷 Mario Pašalić (Croatia)",
  "🇭🇷 Lovro Majer (Croatia)",
  "🇭🇷 Ante Budimir (Croatia)",
  "🇭🇷 Martin Baturina (Croatia)",
  "🇬🇭 Mohammed Kudus (Ghana)",
  "🇬🇭 Jordan Ayew (Ghana)",
  "🇬🇭 Iñaki Williams (Ghana)",
  "🇬🇭 Antoine Semenyo (Ghana)",
  "🇬🇭 Ernest Nuamah (Ghana)",
  "🇬🇭 Kamaldeen Sulemana (Ghana)",
  "🇬🇭 Thomas Partey (Ghana)",
  "🇬🇭 André Ayew (Ghana)",
  "🇵🇦 José Fajardo (Panama)",
  "🇵🇦 Cecilio Waterman (Panama)",
  "🇵🇦 Édgar Bárcenas (Panama)",
  "🇵🇦 Ismael Díaz (Panama)",
  "🇵🇦 Yoel Bárcenas (Panama)",
  "🇵🇦 Alberto Quintero (Panama)",
  "🇵🇦 César Yanis (Panama)",
  "🇵🇦 José Luis Rodríguez (Panama)"
];
